### ISSUE TITLE
Iniciar Projeto React Native

### ISSUE THREAD

**Issue by thiagoalvesfoz** [Projeto-Antlia/antlia#2]
Etapas

 - [x] Eslint
 - [x] Prettier
 - [x] .editorconfig
 - [x] Husky (opcional)
 - [x] Typescript configurado
 - [x] NativeBase
 - [x] Teste configurado com exemplo

**Comment by antiderson** [comment]
Projeto inicado, com as dependencias e a tela home ja finalizada.
